# Generated by Django 4.0.6 on 2022-09-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_remove_place_p_access_remove_place_p_crownded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='p_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='p_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
